# fly.toml app configuration file generated for backend-shy-thunder-2453 on 2025-04-16T16:54:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-shy-thunder-2453'
primary_region = 'cdg'

[build]
dockerfile = "Dockerfile"

[deploy]
  release_command = 'npx prisma migrate deploy'

[processes]
  app = 'node ./dbsetup.js node dist/server.js'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
